[package]
name = "robyn"
version = "0.5.3"
authors = ["Sanskar Jethi <sansyrox@gmail.com>"]
edition = "2018"
description = "A web server that is fast!"
license = "MIT"
homepage = "https://github.com/sansyrox/robyn"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "robyn"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[dependencies.pyo3-asyncio]
version = "0.13.4"
features = []

[dependencies]
tokio = { version = "1.7.0", features = ["full"] }
dashmap = {git = "https://github.com/quake/dashmap", branch = "parking_lot", features = ["parking_lot"]}
anyhow = "1.0.38"
actix-web = "4.0.0-beta.8"
futures-util = "0.3.15"
actix-files = "0.6.0-beta.6"
serde = "1.0.126"
serde_json = "1.0.64"
pythonize = "0.13.0"

[package.metadata.maturin]
name = "robyn"
