# CI to build the Python code

on: [push, pull_request, workflow_dispatch]

name: Python Continuous integration

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r robyn/test-requirements.txt
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Setup Rust part of the project
        run: |
          source $HOME/.cargo/env
          maturin build -i python --release --universal2 --out dist --no-sdist
          pip install --force-reinstall dist/robyn*.whl
      - name: Test with pytest
        run: |
          pytest ./integration_tests
